- name: Demo connect OCP
  hosts: localhost
  module_defaults:
    group/k8s:
      host: https://console-openshift-console.apps.ankh-morpork.cp.fyre.ibm.com
      ca_cert: ./ingress-operator@1653553544.cer
  tasks:
  - block:
    # It's good practice to store login credentials in a secure vault and not
    # directly in playbooks.
    #- include_vars: openshift_passwords.yml

    - name: Log in (obtain access token)
      community.okd.openshift_auth:
        host: "{{ host }}"
        validate_certs: no
        username: "{{ username }}"
        password: "{{ openshift_admin_password }}"
      register: openshift_auth_results

    # Previous task provides the token/api_key, while all other parameters
    # are taken from module_defaults
    - name: Get a list of all pods from any namespace
      kubernetes.core.k8s_info:
        host: "{{ host }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        kind: Pod
      register: pod_list

    always:
    - name: If login succeeded, try to log out (revoke access token)
      when: openshift_auth_results.openshift_auth.api_key is defined
      community.okd.openshift_auth:
        host: "{{ host }}"
        state: absent
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"

